export default [
"./style/VACIO.png",
"./style/Vincent_van_gogh_collection/Irises-1889.jpg",
"./style/Vincent_van_gogh_collection/landscape-with-house-and-ploughman-1889.jpg",
"./style/Vincent_van_gogh_collection/paul-gauguin-s-armchair-1888.jpg",
"./style/Vincent_van_gogh_collection/prisoners-exercising-prisoners-round-1890.jpg",
"./style/Vincent_van_gogh_collection/red-vineyards-at-arles-1888.jpg",
"./style/Vincent_van_gogh_collection/self-portrait-1887.jpg",
"./style/Vincent_van_gogh_collection/self-portrait-with-bandaged-ear-1889.jpg",
"./style/Vincent_van_gogh_collection/StarryNight.jpg",
"./style/Vincent_van_gogh_collection/still-life-vase-with-fifteen-sunflowers-1888.jpg",
"./style/Vincent_van_gogh_collection/wheatfield-with-crows-1890.jpg",
"./style/Pablo_picasso_collection/cat-catching-a-bird-1939.jpg",
"./style/Pablo_picasso_collection/child-with-dove-1901.jpg",
"./style/Pablo_picasso_collection/figures-at-the-seaside-1931.jpg",
"./style/Pablo_picasso_collection/girl-on-the-ball-1905.jpg",
"./style/Pablo_picasso_collection/mujeres_de_argel_picasso.jpg",
"./style/Pablo_picasso_collection/old-guitarist-chicago-1903.jpg",
"./style/Pablo_picasso_collection/portrait-of-ambroise-vollard-1910.jpg",
"./style/Pablo_picasso_collection/portrait-of-dora-maar-1937.jpg",
"./style/Pablo_picasso_collection/Portrait-of-woman-in-dhermine-pass-1937.jpg",
"./style/Pablo_picasso_collection/the-girls-of-avignon-1907.jpg",
"./style/Claude_monet_collection/autumn-on-the-seine-at-argenteuil-1873.jpg",
"./style/Claude_monet_collection/camille-with-green-parasol-1876.jpg",
"./style/Claude_monet_collection/claude-monet-irises-in-monets-garden-1899.jpg",
"./style/Claude_monet_collection/impression-sunrise-1872.jpg",
"./style/Claude_monet_collection/madame-monet-and-child-1875.jpg",
"./style/Claude_monet_collection/poplars-at-giverny-1887.jpg",
"./style/Claude_monet_collection/snow-at-argenteuil-1875.jpg",
"./style/Claude_monet_collection/the-boat-studio-1876.jpg",
"./style/Claude_monet_collection/the-shoot-1876.jpg",
"./style/Claude_monet_collection/waterloo-bridge-london-1903.jpg",
"./style/Edvard_munch_collection/august-stindberg-1892.jpg",
"./style/Edvard_munch_collection/edvard-munch-rosa-meissner.jpg",
"./style/Edvard_munch_collection/girl-combing-her-hair-1892.jpg",
"./style/Edvard_munch_collection/morning-1884.jpg",
"./style/Edvard_munch_collection/portrait-of-the-painter-jensen-hjell-1885.jpg",
"./style/Edvard_munch_collection/Selvportrett-1926.jpg",
"./style/Edvard_munch_collection/spring-day-on-karl-johan-street-1890.jpg",
"./style/Edvard_munch_collection/street-lafayette-1891.jpg",
"./style/Edvard_munch_collection/the-scream-1893.jpg",
"./style/Edvard_munch_collection/view-over-the-rover-at-st-cloud-1890.jpg",
"./style/Pierre_auguste_renoir_collection/banks-of-the-seine-at-champrosay-1876.jpg",
"./style/Pierre_auguste_renoir_collection/by-the-fireside-1875.jpg",
"./style/Pierre_auguste_renoir_collection/by-the-seashore-1883.jpg",
"./style/Pierre_auguste_renoir_collection/girl-gathering-flowers-1872.jpg",
"./style/Pierre_auguste_renoir_collection/girl-with-a-dog-1875.jpg",
"./style/Pierre_auguste_renoir_collection/jeanne-samary-in-a-low-necked-dress-1877.jpg",
"./style/Pierre_auguste_renoir_collection/self-portrait-with-a-white-hat-1910.jpg",
"./style/Pierre_auguste_renoir_collection/the-duck-pond-1873.jpg",
"./style/Pierre_auguste_renoir_collection/the-seine-at-argenteuil-1875.jpg",
"./style/Pierre_auguste_renoir_collection/young-woman-with-a-dog-1876.jpg",
"./style/Pierre_auguste_renoir_collection/young-woman-with-a-japanese-umbrella-1876.jpg",
"./style/Salvador_dali_collection/3salvador-dali-peyzazh-bliz-figerasa-1910.jpg",
"./style/Salvador_dali_collection/boat-1918.jpg",
"./style/Salvador_dali_collection/Dream_for_bee_1944.jpg",
"./style/Salvador_dali_collection/landscape-1916.jpg",
"./style/Salvador_dali_collection/landscape-near-ampurdan-1914.jpg",
"./style/Salvador_dali_collection/llane-beach-cadaques-1919.jpg",
"./style/Salvador_dali_collection/Persistencia_de_la_memoria.jpg",
"./style/Salvador_dali_collection/portdogue-1918.jpg",
"./style/Salvador_dali_collection/the-disintegration-of-the-persistence-of-memory-1952.jpg",
"./style/Salvador_dali_collection/the-great-masturbator-1929.jpg",
"./style/Leonardo_davinci_collection/da-vinci-vitruve-luc-viatour.jpg",
"./style/Leonardo_davinci_collection/drapery-for-a-seated-1470.jpg",
"./style/Leonardo_davinci_collection/mona-lisa.1503.jpg",
"./style/Leonardo_davinci_collection/profile-of-a-warrior-in-helmet-1472.jpg",
"./style/Leonardo_davinci_collection/study-of-hands-1474.jpg",
"./style/Leonardo_davinci_collection/the-baptism-of-christ-c-1475.jpg",
"./style/Leonardo_davinci_collection/the-madonna-of-the-carnation-1480.jpg",
"./style/Leonardo_davinci_collection/the-lady-with-the-ermine-cecilia-gallerani-1496.jpg",
"./style/Leonardo_davinci_collection/Autorretrato.jpg",
"./style/Rembrandt_collection/beggar-man-and-woman-1628.jpg",
"./style/Rembrandt_collection/beggar-man-and-woman-behind-a-bank-1630.jpg",
"./style/Rembrandt_collection/old-man-in-a-long-cloak-sitting-in-an-armchair-1630.jpg",
"./style/Rembrandt_collection/seated-old-man-1630.jpg",
"./style/Rembrandt_collection/self-portrait-1630.jpg",
"./style/Rembrandt_collection/self-portrait-leaning-forward-listening-1628.jpg",
"./style/Rembrandt_collection/st-jerome-kneeling-1630.jpg",
"./style/Rembrandt_collection/st-paul-in-meditation-1629.jpg",
"./style/Rembrandt_collection/the-flight-into-egypt-a-sketch-1627.jpg",
"./style/Rembrandt_collection/widebrim-1632.jpg"












];